name: deskos
description: A Flutter WebView application that works across all platforms
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.2
  webview_flutter_android: ^3.12.1
  webview_flutter_wkwebview: ^3.9.4
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.7
  http: ^1.2.0
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  adaptive_icon_background: "#673AB7" # Purple background
  adaptive_icon_foreground: "assets/icon/icon_foreground.png" # Text or logo with transparency
  ios: true
  image_path: "assets/icon/hollow_icon.png"
  remove_alpha_ios: true # For iOS, removes transparency and applies shape
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    # background_color: "#673AB7"
    theme_color: "#673AB7"
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/app_icon.png"
